name: tim25
channels:
  - conda-forge

dependencies:
  - python==3.10
  - napari==0.5.6
  - pyqt==5.15.9
  - seaborn==0.13.2
  - napari-omero==0.3.0
  - napari-skimage-regionprops==0.10.1
  - napari-accelerated-pixel-and-object-classification==0.14.1
  - napari-clusters-plotter==0.8.1

